Improve AggregateRaster for small source geometries
nens/dask-geomodeling pull request #104
Opened 2023-03-24 13:24 UTC by byrman

2023-03-24 14:11 UTC, arjanverkerk approved these changes

2023-03-27 07:26 UTC, caspervdw requested changes
I recall making the `# snap the extent to (0, 0) to prevent subpixel shift` part to make label computations deterministic.

There was problem that the outcome of an aggregation value depended on other geometries being present. This is because the `extent` is computed based on all geometries in the request. 

I  think that effect is back now as `x2, y1` are not snapped anymore to `(0,0)`.

2023-03-27 07:30 UTC, byrman commented
Have you seen these results: https://github.com/nens/lizard-nxt/issues/5814#issuecomment-1479321495?

2023-03-27 07:52 UTC, caspervdw commented
> Have you seen these results: https://github.com/nens/lizard-nxt/issues/5814#issuecomment-1479321495?

> > I think that effect is back now as x2, y1 are not snapped anymore to (0,0)
> 
> "think"?

Yes I read the issue. I am afraid I don't understand what is happening.
Also I can't oversee the effects of this change completely.

Does this test fail now? https://github.com/nens/dask-geomodeling/blob/111275c33824c4717ee0bd25c7396b963e39abc3/dask_geomodeling/tests/test_geometry.py#L882

I just want to be sure that this solution doesn't break other use cases.

2023-03-27 08:03 UTC, caspervdw commented
>  I'd guess that what is meant is that the rasterization of a particular feature does not depend on the envelope of the group of features that are rasterized together. 

Exactly. Well put!

> the tiniest change in pixel_size may result in a big shift of the bounding box requested to the raster source in the current situation which may have big effects on the rasterization.

I don't get that part. The "big shift" is at maximum 1 cell, right? From what perspective is that big? And in any case, the geometry will be enclosed by the raster. 

What happens in rasterization to a geometry much smaller than 1 cell?

2023-03-27 08:04 UTC, byrman commented
> Does this test fail now?

All pull requests fail, not just mine. I don't know what's wrong with the test setup. I would be happy the run the tests locally in a container (but no Docker file are present).

2023-03-27 08:15 UTC, caspervdw commented
> > Does this test fail now?
> 
> All pull requests fail, not just mine. I don't know what's wrong with the test setup. I would be happy the run the tests locally in a container (but no Docker files are present).

Just make a virtualenv, any python version will do.

2023-03-27 09:17 UTC, arjanverkerk commented
> I don't get that part. The "big shift" is at maximum 1 cell, right? From what perspective is that big? And in any case, the geometry will be enclosed by the raster.

From the perspective of the cells near the edge of a feature it means everything, it means to be included or not. We're talking about the rain raster here, which has 1000 m cells. Of course, one should pick a much smaller pixel_size (supersampling) when the geometry's area is in the same order as the pixel area, and that is what I suggested and @byrman tried. But then he noticed how small pixel_size changes affected the result very much.

> What happens in rasterization to a geometry much smaller than 1 cell?

Good one. In this use case it is not clearly defined. We have a small diamond shaped geometry. When near or at the center of a cell, it gets rasterized. But when it is over the intersection between 4 cells and away from centers, it is not rasterized (Bresenhams line algorithm, not exactly meant for this use case I guess) unless 'ALL_TOUCHED=TRUE'.

2023-03-27 11:02 UTC, closed without merging